### PR TITLE
Fix user_assertions

### PR DESCRIPTION
**Pull request by reupost**
'user_assertions:true' didn't work on our setup, possibly yours is different. It is phrased this way here though: https://github.com/AtlasOfLivingAustralia/alerts/blob/881b156ead541f3b199843f2218f9ad387e1dba9/grails-app/controllers/au/org/ala/alerts/AdminController.groovy#L72

### CODE REVIEW

**Comment by nickdos** [comment]
Yes, the `user_assertions` syntax has changed so thanks for the PR.

**Comment by nickdos** [comment]
Had to manually merge due to conflict. See a3d6a44.

**Comment by vjrj** [comment]
Hi @nickdos , the conflict is because we are trying to remove the harcoded `/ws/` via this PR:
https://github.com/AtlasOfLivingAustralia/alerts/pull/52
I say trying because this should be coherent in the rest of tools, see:
https://github.com/AtlasOfLivingAustralia/alerts/issues/57

**Comment by nickdos** [comment]
I did wonder about the `/ws` difference. I'll just manually fix in Master.

**Pull request closed without merging**
