### PR TITLE
Issue 71

### PR DESCRIPTION
**Pull request by Rita-C**
`cascade: 'all-delete-orphan' `didn't work. 
Can only delete Query when no subscriber.

### CODE REVIEW

**Comment by vjrj** [comment]
Hi @Rita-C , I've tested the deletion and it works great, but when I try to run the same deletion code in:

```
+  int deleteOrphanedQueries(){
     def toBeRemoved = []
     Query.findAll().each {
-        if(it.notifications.size() == 0){
+        if(it.notifications.size() == 0 && it.custom == true){
             toBeRemoved << it
         }
     }
 
     toBeRemoved.each {
-        Query.deleteAll(toBeRemoved)
+        deleteQuery(it)
     }
```

It fails with a sql error
`org.hibernate.exception.SQLGrammarException: could not extract ResultSet`
I have my concerns If the mapping is correct now.

**Comment by vjrj** [comment]
To be more specific, I think that if you create an alert and you delete it directly, it works, but the same does not work for me with older queries (I can imagine that has some `query_result` and `property_path`)

**Comment by Rita-C** [comment]
Hi @vjrj ,
This PR is to fix deleting individual alerts from the admin screen, for fresh or older alerts (entries in `query_result`, `property_value` and `property_path` tables).

The code for `Delete orphaned queries` as you pointed out is broken as it will have FK constraints errors too. I'd like to address this problem in a separate ticket, feel free to raise one or I can do that.

**Comment by vjrj** [comment]
Hi @Rita-C , I tried again to test this (forgetting for a moment the delete orphaned issue), and in some cases I had still this `could not extract ResultSet` error. In other cases, this works perfect.

I tried to recreate the db and I reproduced the error in some cases. The issue arise when `query_result` is empty for some query but `property_path` is not.

Instead this code worked for me for both issues:
```
diff --git a/grails-app/services/au/org/ala/alerts/QueryService.groovy b/grails-app/services/au/org/ala/alerts/QueryService.groovy
index a1c855c..14905b0 100644
--- a/grails-app/services/au/org/ala/alerts/QueryService.groovy
+++ b/grails-app/services/au/org/ala/alerts/QueryService.groovy
@@ -1,6 +1,7 @@
 package au.org.ala.alerts
 
 import grails.util.Holders
+import org.springframework.dao.DataIntegrityViolationException
 
 class QueryService {
 
@@ -49,17 +50,29 @@ class QueryService {
     fireWhenNotZeroValue
   }
 
-  int deleteOrphanedQueries(){
+  def deleteQuery(Query queryInstance) throws DataIntegrityViolationException {
+    def propertyPaths = PropertyPath.findAllByQuery(queryInstance)
+    def queryResults = QueryResult.findAllByQuery(queryInstance)
 
+    if (queryResults.size() > 0) {
+      def propertyValues = PropertyValue.findAllByQueryResultInList(queryResults)
+      PropertyValue.deleteAll(propertyValues)
+    }
+    QueryResult.deleteAll(queryResults)
+    PropertyPath.deleteAll(propertyPaths)
+    queryInstance.delete(flush: true)
+  }
+
+  int deleteOrphanedQueries(){
     def toBeRemoved = []
     Query.findAll().each {
-        if(it.notifications.size() == 0){
+        if(it.notifications.size() == 0 && it.custom == true){
             toBeRemoved << it
         }
     }
 
     toBeRemoved.each {
-        Query.deleteAll(toBeRemoved)
+        deleteQuery(it)
     }
 
     toBeRemoved.size()
```

See the added ` if (queryResults.size() > 0)` condition.

A screenshot of `property_path` with the two last records, causing this issue:

2020-11-10-11-15-18-screenshot

**Comment by Rita-C** [comment]
Thanks @vjrj ,
I've created a new ticket #75 for "Delete orphaned queries", would you like to check in your code change against #75?

**Comment by vjrj** [comment]
Hi @Rita-C . I tested yesterday your PR + my minor code changed against #71 and #75 and it solves both issues.

To be sure, today I've tested it again.

To summary, adding this to your current PR it solves both issues:
```
int deleteOrphanedQueries(){
     def toBeRemoved = []
     Query.findAll().each {
-        if(it.notifications.size() == 0){
-            toBeRemoved << it
-        }
+      if (it.notifications.size() == 0 && it.custom == true) {
+        toBeRemoved << it
+      }
     }
 
     toBeRemoved.each {
-        Query.deleteAll(toBeRemoved)
+      deleteQuery(it)
     }
```
As you see I added a second condition `it.custom == true` to only try to clean orphaned custom queries and not the default ones.

Thanks @Rita-C!

**Comment by Rita-C** [comment]
Hi @vjrj , 
Are you happy for me to merge the changes to dev branch? Then you or I can update `deleteOrphanedQueries`

**Review by vjrj — APPROVED** [review]

**Comment by vjrj** [comment]
Yes, sorry @Rita-C. I forget to press to review it.

**Pull request merged**
